version: '3.7'
services:
  postgres:
    container_name: cloudflare-graphql
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - cloudflare-graphql:/var/lib/postgresql/data
    ports:
      - '25432:5432'
volumes:
  cloudflare-graphql:
